language: go

go:
  - "1.12"
  - master

env:
  - GO111MODULE=on

before_install:
  - go get -v golang.org/x/lint/golint

script:
  - golint ./...
  - go vet ./...
  - go test --race -v -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)
